apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  connection-string: "Host={{ .Values.backend.db.host }};Port={{ .Values.backend.db.port }};Database={{ .Values.backend.db.database }};Username={{ .Values.backend.db.username }};Password={{ .Values.backend.db.password }};"