apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: lms-backend
stringData:
  connection-string: Host=postgres-sts-0.postgres-headless-svc.db.svc.cluster.local;Port=5432;Database=MarketplaceDbs;Username=postgres;Password=postgresmaster;