{{- if .Values.redisInsightIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.fullname" . }}-redis-insight
  namespace: {{ .Values.redisInsightIngress.namespace }}
  labels:
    app: {{ include "ingress.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.redisInsightIngress.ingressClassName }}
  rules:
  - host: {{ .Values.redisInsightIngress.host }}
    http:
      paths:
      - path: {{ .Values.redisInsightIngress.path }}
        pathType: {{ .Values.redisInsightIngress.pathType }}
        backend:
          service:
            name: {{ .Values.redisInsightIngress.serviceName }}
            port:
              number: {{ .Values.redisInsightIngress.servicePort }}
{{- end }}