apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "postgresql.name" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.postgresql }}
      targetPort: 5432
  selector:
    app: {{ include "postgresql.name" . }}