apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app: {{ include "postgresql.name" . }}
spec:
  ports:
    - port: {{ .Values.service.ports.postgresql }}
      targetPort: 5432
  selector:
    app: {{ include "postgresql.name" . }}