apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "backend.fullname" . }}-migrations-cronjob
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "backend.name" . }}
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: migrations
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            command: {{ .Values.migrations.command | toYaml | nindent 12 }}
            env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: connection-string
          restartPolicy: OnFailure