apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lms-app-ingress
  namespace: lms-backend
spec:
  ingressClassName: nginx
  rules:
  - host: lms.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lms-app-service
            port:
              number: 80