apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: redis-insight-ingress
  namespace: db
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: redis-insight.myredis.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-redisinsight
            port:
              number: 5000