apiVersion: v1
kind: Service
metadata:
  name: {{ include "redisinsight.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "redisinsight.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
  selector:
    app: {{ include "redisinsight.name" . }}