apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}-headless
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "redis.name" . }}
spec:
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: {{ include "redis.name" . }}