apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-lb
  labels:
    app: {{ .Release.Name }}-redis
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  selector:
    app: {{ .Release.Name }}-redis